trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- task: AzureCLI@2
  displayName: Install Terraform
  inputs:
    azureSubscription: 'Azure-Service-Connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      wget https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
      unzip terraform_1.9.8_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform version

- task: AzureCLI@2
  displayName: Terraform Init
  inputs:
    azureSubscription: 'Azure-Service-Connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform init

- task: AzureCLI@2
  displayName: Terraform Validate
  inputs:
    azureSubscription: 'Azure-Service-Connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform validate

- task: AzureCLI@2
  displayName: Terraform Plan
  inputs:
    azureSubscription: 'Azure-Service-Connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform plan
